apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: lj3knu3sw-dotnet-basic-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/lj3knu3sw-dotnet-basic-gitops